/// Flutter icons IBuddyIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IBuddyIcons
///      fonts:
///       - asset: fonts/IBuddyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IBuddyIcons {
  IBuddyIcons._();

  static const _kFontFam = 'IBuddyIcons';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
